SLURM_JOBID:  18263353
SLURM_ARRAY_TASK_ID:  48
SLURM_ARRAY_JOB_ID:  18263271
2021-03-19 16:43:39.452548: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2021-03-19 16:43:39.452581: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "graph.py", line 10, in <module>
    seeds = np.load('../seeds.npy')
  File "/home/smaity/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../seeds.npy'
